version: '3'
services:
  app:
    build: .
    container_name: my-node-app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    env_file:
      - .env 
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo:6
    container_name: my-mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
